name: Design Futures
favicon: null
layout_spectrum: 0.85985
typography_spectrum: 0.06319615407846868
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6f5d6'
    - '#00030a'
    - '#526e96'
    - '#78a8bc'
    - '#37413b'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
